name: Fast-Forward PR

on: 
  issue_comment:
    types: [created]

jobs:
  fast_forward_job:
    name: Fast Forward
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/fast-forward')   
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions-cool/check-user-permission@a0668c9aec87f3875fc56170b6452a453e9dd819
        with:
          require: admin
        id: check-user-permission
      - name: Check permission
        if: not steps.check-user-permission.outputs.require-result
        run: exit 1
      - uses: hmarr/auto-approve-action@v3
        with:
          pull-request-number: ${{ github.event.issue.number }}
      # To use this repository's private action, you must check out the repository
      - name: Checkout code into workspace directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # Basic use case example
      - name: Fast Forward PR
        id: ff-action
        uses: endre-spotlab/fast-forward-js-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          success_message: 'Success! Fast forwarded ***target_base*** to ***source_head***! ```git checkout target_base && git merge source_head --ff-only``` '
          failure_message: 'Failed! Cannot do fast forward!'
          staging_branch: 'staging'
          production_branch: 'master'
